---
Name: silverstripe-fluent-autotranslate
---
SilverStripe\Forms\TextField:
  extensions:
    - Level51\Autotranslate\AutotranslateFieldExtension

SilverStripe\Forms\TextareaField:
  extensions:
    - Level51\Autotranslate\AutotranslateFieldExtension

---
Only:
  moduleexists: 'dnadesign/silverstripe-elemental'
---
DNADesign\Elemental\Forms\TextCheckboxGroupField:
  extensions:
    - Level51\Autotranslate\AutotranslateFieldExtension
